# Redirection HTTP → HTTPS
server {
    listen 80;
    server_name nlp-assistant.duckdns.org;

    # Set client_max_body_size to 50M
    client_max_body_size 50M;

    # Nécessaire pour le renouvellement Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Serveur HTTPS
server {
    listen 443 ssl;
    server_name nlp-assistant.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/nlp-assistant.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nlp-assistant.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Set client_max_body_size to 50M
    client_max_body_size 50M;

    location /api/static/ {
        alias /app/app/static/;
        autoindex on;
    }

    location / {
        proxy_pass         http://api:5000;



        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}